### ISSUE TITLE
setImmediate

### ISSUE THREAD

**Issue by pspeter3** [perry-mitchell/lamd#3]
Why does `lamd` use `setImmediate` if you expect all of the dependencies to be on the client?

**Comment by perry-mitchell** [comment]
`setImmediate` is optional, and preferred for performance over setTimeout. I use `setImmediate` to ensure an asynchronous call to the require block. What would you propose?

**Comment by sallar** [comment]
Since there is a check for native `setImmediate` function and it isn’t forced, I don’t see any issues regarding using that instead of `setTimeout(fn, 0)`. `setImmediate` is proven to be faster. 
http://stackoverflow.com/questions/24117267/nodejs-settimeoutfn-0-vs-setimmediatefun  
But if you mean why use these at all and why not just fire the callback, it’s because we don’t want it to be blocking.

**Comment by pspeter3** [comment]
Sorry, I think my question wasn't clear. Why did you choose to have the modules be asynchronous when you know that all of them must be locally defined?

**Comment by perry-mitchell** [comment]
Ah, good point. I created LAMD with my work originally in mind, and we use quite a large script with this library (many modules). Building can take some time, and it became obvious that synchronously loading all modules at once would be a performance hit in some situations. I felt it was better to asynchronously execute each module, so the system could get to executing each block when it's ready and prevent blocking the page.

The `require` and `define` functions should be seen as taking callbacks, and callbacks (in well-designed systems, IMO) are not usually fired synchronously.

**Comment by perry-mitchell** [comment]
I'd like to think as well that making the system async from the start would prove to be a smarter move when it comes to modules that may be loaded later, or require some external condition to be fulfilled before they can actually be defined. Keeping async as the default also keeps the system very consistent, and the implementation slightly simpler.

**Comment by perry-mitchell** [comment]
Closed due to inactivity.
